// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: uno.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from uno.proto</summary>
public static partial class UnoReflection {

  #region Descriptor
  /// <summary>File descriptor for uno.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UnoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgl1bm8ucHJvdG8iNwoIdW5vX2NhcmQSDwoHY2FyZF9pZBgBIAIoDRINCgVj",
          "b2xvchgCIAIoDRILCgNudW0YAyACKA0iOAoIaW5pdF90b2MSEgoKcGxheWVy",
          "X251bRgBIAIoDRIYCgVjYXJkcxgCIAMoCzIJLnVub19jYXJkIjkKF290aGVy",
          "X2FkZF9oYW5kX2NhcmRfdG9jEhEKCXBsYXllcl9pZBgBIAIoDRILCgNudW0Y",
          "AiACKA0iKAoNZHJhd19jYXJkX3RvYxIXCgRjYXJkGAEgAygLMgkudW5vX2Nh",
          "cmQiMQoPbm90aWZ5X3R1cm5fdG9jEhEKCXBsYXllcl9pZBgBIAIoDRILCgNk",
          "aXIYAiACKAgiHwoQc2V0X2RlY2tfbnVtX3RvYxILCgNudW0YASACKA0iNwoQ",
          "ZGlzY2FyZF9jYXJkX3RvcxIPCgdjYXJkX2lkGAEgAigNEhIKCndhbnRfY29s",
          "b3IYAiABKA0iUgoQZGlzY2FyZF9jYXJkX3RvYxIRCglwbGF5ZXJfaWQYASAC",
          "KA0SFwoEY2FyZBgCIAIoCzIJLnVub19jYXJkEhIKCndhbnRfY29sb3IYAyAB",
          "KA1CEFoOcHJvdG9zLztwcm90b3M="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::uno_card), global::uno_card.Parser, new[]{ "CardId", "Color", "Num" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::init_toc), global::init_toc.Parser, new[]{ "PlayerNum", "Cards" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::other_add_hand_card_toc), global::other_add_hand_card_toc.Parser, new[]{ "PlayerId", "Num" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::draw_card_toc), global::draw_card_toc.Parser, new[]{ "Card" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::notify_turn_toc), global::notify_turn_toc.Parser, new[]{ "PlayerId", "Dir" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::set_deck_num_toc), global::set_deck_num_toc.Parser, new[]{ "Num" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::discard_card_tos), global::discard_card_tos.Parser, new[]{ "CardId", "WantColor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::discard_card_toc), global::discard_card_toc.Parser, new[]{ "PlayerId", "Card", "WantColor" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 卡牌的结构体
/// </summary>
public sealed partial class uno_card : pb::IMessage<uno_card> {
  private static readonly pb::MessageParser<uno_card> _parser = new pb::MessageParser<uno_card>(() => new uno_card());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<uno_card> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uno_card() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uno_card(uno_card other) : this() {
    _hasBits0 = other._hasBits0;
    cardId_ = other.cardId_;
    color_ = other.color_;
    num_ = other.num_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uno_card Clone() {
    return new uno_card(this);
  }

  /// <summary>Field number for the "card_id" field.</summary>
  public const int CardIdFieldNumber = 1;
  private readonly static uint CardIdDefaultValue = 0;

  private uint cardId_;
  /// <summary>
  /// 卡牌ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint CardId {
    get { if ((_hasBits0 & 1) != 0) { return cardId_; } else { return CardIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      cardId_ = value;
    }
  }
  /// <summary>Gets whether the "card_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCardId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "card_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCardId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "color" field.</summary>
  public const int ColorFieldNumber = 2;
  private readonly static uint ColorDefaultValue = 0;

  private uint color_;
  /// <summary>
  /// 1、2、3、4代表四种颜色，你爱用哪个用哪个，等价的。0代表黑牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Color {
    get { if ((_hasBits0 & 2) != 0) { return color_; } else { return ColorDefaultValue; } }
    set {
      _hasBits0 |= 2;
      color_ = value;
    }
  }
  /// <summary>Gets whether the "color" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasColor {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "color" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearColor() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 3;
  private readonly static uint NumDefaultValue = 0;

  private uint num_;
  /// <summary>
  /// 0-9是数字牌 10代表“跳过”牌 11代表“反向”牌 12代表“+2牌” 13代表黑牌中的变色牌 14代表黑牌中的“+4”牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Num {
    get { if ((_hasBits0 & 4) != 0) { return num_; } else { return NumDefaultValue; } }
    set {
      _hasBits0 |= 4;
      num_ = value;
    }
  }
  /// <summary>Gets whether the "num" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNum {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "num" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNum() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as uno_card);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(uno_card other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CardId != other.CardId) return false;
    if (Color != other.Color) return false;
    if (Num != other.Num) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCardId) hash ^= CardId.GetHashCode();
    if (HasColor) hash ^= Color.GetHashCode();
    if (HasNum) hash ^= Num.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasCardId) {
      output.WriteRawTag(8);
      output.WriteUInt32(CardId);
    }
    if (HasColor) {
      output.WriteRawTag(16);
      output.WriteUInt32(Color);
    }
    if (HasNum) {
      output.WriteRawTag(24);
      output.WriteUInt32(Num);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasCardId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CardId);
    }
    if (HasColor) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Color);
    }
    if (HasNum) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(uno_card other) {
    if (other == null) {
      return;
    }
    if (other.HasCardId) {
      CardId = other.CardId;
    }
    if (other.HasColor) {
      Color = other.Color;
    }
    if (other.HasNum) {
      Num = other.Num;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CardId = input.ReadUInt32();
          break;
        }
        case 16: {
          Color = input.ReadUInt32();
          break;
        }
        case 24: {
          Num = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：初始化游戏
/// </summary>
public sealed partial class init_toc : pb::IMessage<init_toc> {
  private static readonly pb::MessageParser<init_toc> _parser = new pb::MessageParser<init_toc>(() => new init_toc());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<init_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public init_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public init_toc(init_toc other) : this() {
    _hasBits0 = other._hasBits0;
    playerNum_ = other.playerNum_;
    cards_ = other.cards_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public init_toc Clone() {
    return new init_toc(this);
  }

  /// <summary>Field number for the "player_num" field.</summary>
  public const int PlayerNumFieldNumber = 1;
  private readonly static uint PlayerNumDefaultValue = 0;

  private uint playerNum_;
  /// <summary>
  /// 玩家总人数（包括你）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PlayerNum {
    get { if ((_hasBits0 & 1) != 0) { return playerNum_; } else { return PlayerNumDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerNum_ = value;
    }
  }
  /// <summary>Gets whether the "player_num" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerNum {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "player_num" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerNum() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "cards" field.</summary>
  public const int CardsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::uno_card> _repeated_cards_codec
      = pb::FieldCodec.ForMessage(18, global::uno_card.Parser);
  private readonly pbc::RepeatedField<global::uno_card> cards_ = new pbc::RepeatedField<global::uno_card>();
  /// <summary>
  /// 你的初始手牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::uno_card> Cards {
    get { return cards_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as init_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(init_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerNum != other.PlayerNum) return false;
    if(!cards_.Equals(other.cards_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerNum) hash ^= PlayerNum.GetHashCode();
    hash ^= cards_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPlayerNum) {
      output.WriteRawTag(8);
      output.WriteUInt32(PlayerNum);
    }
    cards_.WriteTo(output, _repeated_cards_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerNum) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerNum);
    }
    size += cards_.CalculateSize(_repeated_cards_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(init_toc other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerNum) {
      PlayerNum = other.PlayerNum;
    }
    cards_.Add(other.cards_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerNum = input.ReadUInt32();
          break;
        }
        case 18: {
          cards_.AddEntriesFrom(input, _repeated_cards_codec);
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：其他玩家摸牌
/// </summary>
public sealed partial class other_add_hand_card_toc : pb::IMessage<other_add_hand_card_toc> {
  private static readonly pb::MessageParser<other_add_hand_card_toc> _parser = new pb::MessageParser<other_add_hand_card_toc>(() => new other_add_hand_card_toc());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<other_add_hand_card_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public other_add_hand_card_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public other_add_hand_card_toc(other_add_hand_card_toc other) : this() {
    _hasBits0 = other._hasBits0;
    playerId_ = other.playerId_;
    num_ = other.num_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public other_add_hand_card_toc Clone() {
    return new other_add_hand_card_toc(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private readonly static uint PlayerIdDefaultValue = 0;

  private uint playerId_;
  /// <summary>
  /// 玩家ID 你的下家是1 下下家是2 以此类推
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PlayerId {
    get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerId_ = value;
    }
  }
  /// <summary>Gets whether the "player_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "player_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 2;
  private readonly static uint NumDefaultValue = 0;

  private uint num_;
  /// <summary>
  /// 增加的手牌数量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Num {
    get { if ((_hasBits0 & 2) != 0) { return num_; } else { return NumDefaultValue; } }
    set {
      _hasBits0 |= 2;
      num_ = value;
    }
  }
  /// <summary>Gets whether the "num" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNum {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "num" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNum() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as other_add_hand_card_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(other_add_hand_card_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (Num != other.Num) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasNum) hash ^= Num.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPlayerId) {
      output.WriteRawTag(8);
      output.WriteUInt32(PlayerId);
    }
    if (HasNum) {
      output.WriteRawTag(16);
      output.WriteUInt32(Num);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
    }
    if (HasNum) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(other_add_hand_card_toc other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasNum) {
      Num = other.Num;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerId = input.ReadUInt32();
          break;
        }
        case 16: {
          Num = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：你摸牌
/// </summary>
public sealed partial class draw_card_toc : pb::IMessage<draw_card_toc> {
  private static readonly pb::MessageParser<draw_card_toc> _parser = new pb::MessageParser<draw_card_toc>(() => new draw_card_toc());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<draw_card_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public draw_card_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public draw_card_toc(draw_card_toc other) : this() {
    card_ = other.card_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public draw_card_toc Clone() {
    return new draw_card_toc(this);
  }

  /// <summary>Field number for the "card" field.</summary>
  public const int CardFieldNumber = 1;
  private static readonly pb::FieldCodec<global::uno_card> _repeated_card_codec
      = pb::FieldCodec.ForMessage(10, global::uno_card.Parser);
  private readonly pbc::RepeatedField<global::uno_card> card_ = new pbc::RepeatedField<global::uno_card>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::uno_card> Card {
    get { return card_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as draw_card_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(draw_card_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!card_.Equals(other.card_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= card_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    card_.WriteTo(output, _repeated_card_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += card_.CalculateSize(_repeated_card_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(draw_card_toc other) {
    if (other == null) {
      return;
    }
    card_.Add(other.card_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          card_.AddEntriesFrom(input, _repeated_card_codec);
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：现在到谁的回合了
/// </summary>
public sealed partial class notify_turn_toc : pb::IMessage<notify_turn_toc> {
  private static readonly pb::MessageParser<notify_turn_toc> _parser = new pb::MessageParser<notify_turn_toc>(() => new notify_turn_toc());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<notify_turn_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public notify_turn_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public notify_turn_toc(notify_turn_toc other) : this() {
    _hasBits0 = other._hasBits0;
    playerId_ = other.playerId_;
    dir_ = other.dir_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public notify_turn_toc Clone() {
    return new notify_turn_toc(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private readonly static uint PlayerIdDefaultValue = 0;

  private uint playerId_;
  /// <summary>
  /// 玩家ID 你是0 你的下家是1 下下家是2 以此类推
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PlayerId {
    get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerId_ = value;
    }
  }
  /// <summary>Gets whether the "player_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "player_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "dir" field.</summary>
  public const int DirFieldNumber = 2;
  private readonly static bool DirDefaultValue = false;

  private bool dir_;
  /// <summary>
  /// true-顺时针 false-逆时针
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Dir {
    get { if ((_hasBits0 & 2) != 0) { return dir_; } else { return DirDefaultValue; } }
    set {
      _hasBits0 |= 2;
      dir_ = value;
    }
  }
  /// <summary>Gets whether the "dir" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDir {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "dir" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDir() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as notify_turn_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(notify_turn_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (Dir != other.Dir) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasDir) hash ^= Dir.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPlayerId) {
      output.WriteRawTag(8);
      output.WriteUInt32(PlayerId);
    }
    if (HasDir) {
      output.WriteRawTag(16);
      output.WriteBool(Dir);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
    }
    if (HasDir) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(notify_turn_toc other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasDir) {
      Dir = other.Dir;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerId = input.ReadUInt32();
          break;
        }
        case 16: {
          Dir = input.ReadBool();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：牌堆剩余数量（如果变多了，说明洗牌了）
/// </summary>
public sealed partial class set_deck_num_toc : pb::IMessage<set_deck_num_toc> {
  private static readonly pb::MessageParser<set_deck_num_toc> _parser = new pb::MessageParser<set_deck_num_toc>(() => new set_deck_num_toc());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<set_deck_num_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public set_deck_num_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public set_deck_num_toc(set_deck_num_toc other) : this() {
    _hasBits0 = other._hasBits0;
    num_ = other.num_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public set_deck_num_toc Clone() {
    return new set_deck_num_toc(this);
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 1;
  private readonly static uint NumDefaultValue = 0;

  private uint num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Num {
    get { if ((_hasBits0 & 1) != 0) { return num_; } else { return NumDefaultValue; } }
    set {
      _hasBits0 |= 1;
      num_ = value;
    }
  }
  /// <summary>Gets whether the "num" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNum {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "num" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNum() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as set_deck_num_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(set_deck_num_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Num != other.Num) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasNum) hash ^= Num.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasNum) {
      output.WriteRawTag(8);
      output.WriteUInt32(Num);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasNum) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(set_deck_num_toc other) {
    if (other == null) {
      return;
    }
    if (other.HasNum) {
      Num = other.Num;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Num = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 出牌
/// </summary>
public sealed partial class discard_card_tos : pb::IMessage<discard_card_tos> {
  private static readonly pb::MessageParser<discard_card_tos> _parser = new pb::MessageParser<discard_card_tos>(() => new discard_card_tos());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<discard_card_tos> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_tos() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_tos(discard_card_tos other) : this() {
    _hasBits0 = other._hasBits0;
    cardId_ = other.cardId_;
    wantColor_ = other.wantColor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_tos Clone() {
    return new discard_card_tos(this);
  }

  /// <summary>Field number for the "card_id" field.</summary>
  public const int CardIdFieldNumber = 1;
  private readonly static uint CardIdDefaultValue = 0;

  private uint cardId_;
  /// <summary>
  /// 出的牌的ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint CardId {
    get { if ((_hasBits0 & 1) != 0) { return cardId_; } else { return CardIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      cardId_ = value;
    }
  }
  /// <summary>Gets whether the "card_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCardId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "card_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCardId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "want_color" field.</summary>
  public const int WantColorFieldNumber = 2;
  private readonly static uint WantColorDefaultValue = 0;

  private uint wantColor_;
  /// <summary>
  /// 出黑牌时，选择想要的颜色
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint WantColor {
    get { if ((_hasBits0 & 2) != 0) { return wantColor_; } else { return WantColorDefaultValue; } }
    set {
      _hasBits0 |= 2;
      wantColor_ = value;
    }
  }
  /// <summary>Gets whether the "want_color" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWantColor {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "want_color" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWantColor() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as discard_card_tos);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(discard_card_tos other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CardId != other.CardId) return false;
    if (WantColor != other.WantColor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCardId) hash ^= CardId.GetHashCode();
    if (HasWantColor) hash ^= WantColor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasCardId) {
      output.WriteRawTag(8);
      output.WriteUInt32(CardId);
    }
    if (HasWantColor) {
      output.WriteRawTag(16);
      output.WriteUInt32(WantColor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasCardId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CardId);
    }
    if (HasWantColor) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WantColor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(discard_card_tos other) {
    if (other == null) {
      return;
    }
    if (other.HasCardId) {
      CardId = other.CardId;
    }
    if (other.HasWantColor) {
      WantColor = other.WantColor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CardId = input.ReadUInt32();
          break;
        }
        case 16: {
          WantColor = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
/// 通知客户端：某玩家出牌（自己出牌后，服务端也会返回这个协议）
/// </summary>
public sealed partial class discard_card_toc : pb::IMessage<discard_card_toc> {
  private static readonly pb::MessageParser<discard_card_toc> _parser = new pb::MessageParser<discard_card_toc>(() => new discard_card_toc());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<discard_card_toc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnoReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_toc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_toc(discard_card_toc other) : this() {
    _hasBits0 = other._hasBits0;
    playerId_ = other.playerId_;
    card_ = other.HasCard ? other.card_.Clone() : null;
    wantColor_ = other.wantColor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public discard_card_toc Clone() {
    return new discard_card_toc(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private readonly static uint PlayerIdDefaultValue = 0;

  private uint playerId_;
  /// <summary>
  /// 玩家ID 你是0 你的下家是1 下下家是2 以此类推
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint PlayerId {
    get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerId_ = value;
    }
  }
  /// <summary>Gets whether the "player_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "player_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "card" field.</summary>
  public const int CardFieldNumber = 2;
  private global::uno_card card_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::uno_card Card {
    get { return card_; }
    set {
      card_ = value;
    }
  }
  /// <summary>Gets whether the card field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCard {
    get { return card_ != null; }
  }
  /// <summary>Clears the value of the card field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCard() {
    card_ = null;
  }

  /// <summary>Field number for the "want_color" field.</summary>
  public const int WantColorFieldNumber = 3;
  private readonly static uint WantColorDefaultValue = 0;

  private uint wantColor_;
  /// <summary>
  /// 出黑牌时，选择想要的颜色
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint WantColor {
    get { if ((_hasBits0 & 2) != 0) { return wantColor_; } else { return WantColorDefaultValue; } }
    set {
      _hasBits0 |= 2;
      wantColor_ = value;
    }
  }
  /// <summary>Gets whether the "want_color" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasWantColor {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "want_color" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearWantColor() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as discard_card_toc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(discard_card_toc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (!object.Equals(Card, other.Card)) return false;
    if (WantColor != other.WantColor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasCard) hash ^= Card.GetHashCode();
    if (HasWantColor) hash ^= WantColor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPlayerId) {
      output.WriteRawTag(8);
      output.WriteUInt32(PlayerId);
    }
    if (HasCard) {
      output.WriteRawTag(18);
      output.WriteMessage(Card);
    }
    if (HasWantColor) {
      output.WriteRawTag(24);
      output.WriteUInt32(WantColor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerId);
    }
    if (HasCard) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Card);
    }
    if (HasWantColor) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WantColor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(discard_card_toc other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasCard) {
      if (!HasCard) {
        Card = new global::uno_card();
      }
      Card.MergeFrom(other.Card);
    }
    if (other.HasWantColor) {
      WantColor = other.WantColor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerId = input.ReadUInt32();
          break;
        }
        case 18: {
          if (!HasCard) {
            Card = new global::uno_card();
          }
          input.ReadMessage(Card);
          break;
        }
        case 24: {
          WantColor = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
